"""empty message

Revision ID: 6c879da75469
Revises: 370619e06feb
Create Date: 2021-12-24 16:13:11.050055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c879da75469'
down_revision = '370619e06feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
